name: Release

on:
  workflow_run:
    workflows: [ "CI" ]
    branches: [ "master" ]
    types: [ completed ]

jobs:
  release:
    name: Release artifacts
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.0
    - name: Set up JDK 11
      uses: actions/setup-java@v4.0.0
      with:
        java-version: '11'
        distribution: 'temurin'

    - name: Cache sbt
      uses: actions/cache@v3.3.3
      with:
        path: |
          ~/.sbt
          ~/.ivy2/cache
          ~/.coursier/cache/v1
          ~/.cache/coursier/v1
          ~/AppData/Local/Coursier/Cache/v1
          ~/Library/Caches/Coursier/v1
        key: ${{ runner.os }}-sbt-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}

    - name: Setup GPG
      run: |
        echo "$PGP_SECRET" | base64 --decode | gpg --batch --import
        mkdir -p "$HOME/.ivy2"
        echo -e "realm=Dummy\nhost=example.com\nuser=user\npassword=password" > "$HOME/.ivy2/.credentials_nexus"
      env:
        PGP_SECRET: ${{ secrets.PGP_SECRET }}

    - name: Build and publish
      run: sbt +clean +publishSigned sonatypeBundleRelease
      env:
        PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
        SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
        SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
